# Build your own messages. I'm not very creative.
# Templates:
#  - {PLAYER}, a format of "Player RP name (Player MC Name)" of the person who was exiled
#  - {REASON}, the reason provided by the accusor of the exile
broadcast:
  enabled: false
  messages:
    - By divine decree {PLAYER} has been exiled!
#   - {PLAYER} was exiled! Reason: {REASON}!

# Whether or not the exiled player should know who exiled them
exile.knows.exiler: true